server:
  port: 8443

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/white_jotter?erverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml

#showSql
logging:
  level:
    com:
      evan:
        wj:
          mapper: debug
