server:
  port: 8443

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/white_jotter?erverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
